require "rails_helper"

RSpec.describe Tenancy::MigrationHelpers do
  let(:connection) { SchemaOwnerRecord.lease_connection }

  def run_migration(&block)
    migration = Class.new(ActiveRecord::Migration[8.1]) { define_method(:change, &block) }
    ActiveRecord::Migration.suppress_messages { migration.new.exec_migration(connection, :up) }
  end

  def index_for(*columns)
    connection.indexes(:widgets).find { |index| index.columns == columns.map(&:to_s) }
  end

  before do
    run_migration do
      tenant_scoped_table :widgets, unique: [:code, [:kind, :size]] do |t|
        t.text :code, null: false
        t.text :kind
        t.text :size
      end
    end
  end

  it "gives the table a uuid primary key generated by the database" do
    column = connection.columns(:widgets).find { |c| c.name == "id" }

    expect(column.type).to eq(:uuid)
    expect(column.default_function).to eq("uuidv7()")
  end

  it "adds a non-null uuid tenant_id" do
    column = connection.columns(:widgets).find { |c| c.name == "tenant_id" }

    expect(column.type).to eq(:uuid)
    expect(column.null).to be(false)
  end

  it "adds a cascading foreign key to tenants" do
    foreign_key = connection.foreign_keys(:widgets).first

    expect(foreign_key.to_table).to eq("tenants")
    expect(foreign_key.on_delete).to eq(:cascade)
  end

  it "indexes tenant_id on its own" do
    expect(index_for(:tenant_id)).to be_present
  end

  it "makes per-tenant unique indexes lead with tenant_id" do
    expect(index_for(:tenant_id, :code).unique).to be(true)
  end

  it "supports composite per-tenant unique indexes" do
    expect(index_for(:tenant_id, :kind, :size).unique).to be(true)
  end

  it "adds timestamps with a time zone" do
    created_at = connection.columns(:widgets).find { |c| c.name == "created_at" }

    expect(created_at.sql_type).to include("with time zone")
  end

  it "enables row-level security with the tenant isolation policy" do
    enabled = connection.select_value("SELECT relrowsecurity FROM pg_class WHERE relname = 'widgets'")
    policies = connection.select_values("SELECT policyname FROM pg_policies WHERE tablename = 'widgets'")

    expect(enabled).to be(true)
    expect(policies).to eq(["tenant_isolation"])
  end

  # The owner writes both rows, because the app role's uncommitted tenant is
  # invisible to the owner's connection.
  it "cascades deletes from the owning tenant" do
    tenant_id = connection.select_value(
      "INSERT INTO tenants (name, slug, created_at, updated_at) VALUES ('w', 'w', now(), now()) RETURNING id"
    )
    connection.execute(
      "INSERT INTO widgets (tenant_id, code, created_at, updated_at) " \
      "VALUES ('#{tenant_id}', 'w1', now(), now())"
    )

    connection.execute("DELETE FROM tenants WHERE id = '#{tenant_id}'")

    expect(connection.select_value("SELECT count(*) FROM widgets")).to eq(0)
  end

  describe "one_row_per_tenant" do
    before { run_migration { tenant_scoped_table :gizmos, one_row_per_tenant: true } }

    after { connection.drop_table :gizmos, if_exists: true }

    it "makes the tenant_id index unique" do
      index = connection.indexes(:gizmos).find { |i| i.columns == ["tenant_id"] }

      expect(index.unique).to be(true)
    end

    it "does not leave a redundant second index on tenant_id" do
      indexes = connection.indexes(:gizmos).select { |i| i.columns == ["tenant_id"] }

      expect(indexes.size).to eq(1)
    end
  end

  it "accepts a table with no columns of its own" do
    run_migration { tenant_scoped_table :gadgets }

    expect(connection.columns(:gadgets).map(&:name)).to include("tenant_id")
  end
end
